### ISSUE TITLE
Configurable lighting

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#15]
Currently, [two lights](https://github.com/gohyperr/hecs/blob/95032b1/packages/hecs-plugin-three/src/Presentation.js#L85) are created for the scene by default, a HemisphereLight and a DirectionalLight.

This setup makes it really nice to get started, but lacks configurability.

I'd like to try different light settings in my scene. For example, it would be helpful to try different light positions or change the shadow map width and height.

Is there a direction planned for this type of lighting customization?

**Comment by ashconnell** [comment]
I've been meaning to come up with a better way to configure this per project. For now my own project just removes those lights immediately and then adds whatever it needs to the scene manually by accessing `world.presentation.scene`.
