### ISSUE TITLE
Black "flash screen" when resizing

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#16]
When resizing the canvas (i.e. browser window) the renderer flashes a black color, painting over the scene. (The scene is restored after finalizing the window size).

I'm using Firefox.

**Comment by ashconnell** [comment]
Easy fix: https://github.com/pixijs/pixi.js/issues/3395#issuecomment-328495407

I'll push this up

**Comment by canadaduane** [comment]
Awesome!!

**Comment by canadaduane** [comment]
I checked and it looks good!
