### ISSUE TITLE
hecs-example introduces three as a HECS dependency

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#17]
Prior to `hecs-example`'s inclusion in the monorepo, three.js was a peerDependency of HECS. Now, however, it appears three is a versioned dependency.

I see the following warning in my webpack build log:

```
WARNING in three
  Multiple versions of three found:
    0.119.1 /Users/duane/tmp/hecs/~/three
    0.121.1 ./~/three
```

(With thanks to `duplicate-package-checker-webpack-plugin`).

**Comment by ashconnell** [comment]
Ah yes I should use the same version everywhere. I copy pasted that code from the codesandbox example 😓

**Comment by canadaduane** [comment]
We're net better off with the example! :)

**Comment by ashconnell** [comment]
Oh you must be using 1.121.1 explicitly in your project. `hecs-example` was set to `0.119.1` so i've updated it to match the same semver pattern as `hecs-plugin-three`: `^0.119.1`

**Comment by canadaduane** [comment]
I still get a warning that two versions of three are included in my package. For now, I've moved my project to depend on the same version as HECS, "^0.119.1".

**Comment by ashconnell** [comment]
How can I reproduce this warning?

**Comment by canadaduane** [comment]
Strangely, I'm unable to reproduce this now. I tried putting it back to `1.121.0` in my experimental project, and also tried creating a new repo. If I see this message again, I'll let you know and add a repro.

**Comment by ashconnell** [comment]
When i ran `yarn` again on master it updated the lock file to remove a duplicate `three` entry. I pushed that change up.

I think this is resolved now anyway right?

**Comment by canadaduane** [comment]
Sounds good, thanks. I also used a (perhaps temporary) workaround using webpack's `resolve.alias` functionality:

```
  resolve: {
    //
    // modules: [path.resolve(__dirname, "src")],
    alias: {
      // Resolve only one version of threejs
      three: path.resolve("node_modules", "three"),
    }
...
```

At some point I'll check if that can be removed in my project.
