### ISSUE TITLE
Example in README should statically reference queries

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#2]
When trying out the example in the README, I noticed the following error from typescript:

```
Property 'queries' is a static member of type 'ModelSystem'
```

I think the references in `update` to `this.queries` should be replaced with `ModelSystem.queries`:

```
  update() {
    ModelSystem.queries.added.forEach((entity) => {
      const model = entity.get(Model);
      const object3d = getModel(model.type);
      entity.add(Mesh, { value: object3d });
    });
    ModelSystem.queries.modified.forEach((entity) => {
      entity.remove(Mesh);
      const model = entity.get(Model);
      const object3d = getModel(model.type);
      entity.add(Mesh, { value: object3d });
    });
    ModelSystem.queries.removed.forEach((entity) => {
      const object3d = entity.get(Mesh).value;
      object3d.dispose();
      entity.remove(Mesh);
    });
  }
```

**Comment by ashconnell** [comment]
I haven't tried to use this with Typescript yet but that code doesn't look right to me. Internally the queries are built and added to the system instance, not the constructor.

**Comment by canadaduane** [comment]
Ah, I see. Somehow, Typescript doesn't see that `queries` is both a static class object and an instance object.
