### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#20]
I'd like to propose some kind of plugin settings or config block.

Currently, the only way to pass something in to a plugin is as a global (e.g. PhysX). This is less than ideal, and I think a configuration block would help here.

**My use case:** I've built a new plugin, [hecs-plugin-rapier](https://github.com/relm-us/relm-experimental/tree/main/src/plugins/hecs-plugin-rapier), and I've hard-coded a dependency on [hecs-plugin-composable](https://github.com/gohyperr/hecs/pull/18) by using `ComposableTransform` throughout; however, `hecs-plugin-rapier` could work just as well with the `hecs-plugin-core` Transform component as the ComposableTransform component. In other words, if there were a config block for plugins, I could allow the user of `hecs-plugin-rapier` decide which "Transform" component to use, and users of this plugin would not have to buy in to the `hecs-plugin-composable` way of doing things if they didn't want to.

**Comment by ashconnell** [comment]
Does the `decorate()` function not help here? Your rapier plugin could have something like `world.physics.setComposableTransforms(Boolean)` or `world.physics.configure({ composableTransforms: true })`

**Comment by canadaduane** [comment]
It might help. How would I intercept the query-builder that converts static `queries` to instance `queries` here?

```
...
import { ComposableTransform } from "hecs-plugin-composable";

export class PhysicsSystem extends System {
  order = Groups.Simulation;

  static queries = {
    default: [RigidBodyRef, ComposableTransform, WorldTransform],
  };
...
```

Maybe if there were a way to construct `this.queries` with a parameterized function...? But then I guess I would need to do it inside the `System.init()` method... maybe I could call `this.world.queries.create(...)` dynamically there. Hmmm....

**Comment by canadaduane** [comment]
See also #23 as an example use case

**Comment by ashconnell** [comment]
I see your problem but I'm not 100% sure what the best way to solve it would be.

I prefer that my systems are simple and do one very specific thing really well. I suspect trying to make a system work differently based on params is like an ECS code smell.

**Comment by ashconnell** [comment]
I propose we just do this as it's much simpler. Let me know what you think. https://github.com/gohyperr/hecs/pull/26#issuecomment-730060336

**Comment by canadaduane** [comment]
I think this is a great way forward. Thanks!
