### ISSUE TITLE
Default directional light has unnecessary bias of -0.01

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#25]
I was trying to figure out why my shadows were all "offset" by a certain amount:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/129/98447080-6937ea00-20df-11eb-9aa4-7c9478d22b41.png">

It turns out this [bias setting](https://github.com/gohyperr/hecs/blob/master/packages/hecs-plugin-three/src/Presentation.js#L104) is the cause:

```
dirLight.shadow.bias = -0.01
```

Shadows looks better when I comment that line out:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/129/98447092-76ed6f80-20df-11eb-8daf-631b08daef42.png">

**Comment by ashconnell** [comment]
Yeah i think depending on your setup you may want this different. Configurable plugins should solve it

**Comment by canadaduane** [comment]
Sounds reasonable. Thanks.
