### ISSUE TITLE
Uncaught Error: hecs: component already registered 'Model'

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#6]
I'm struggling to get the plugin system to work with any bundler (started with rollup, now trying webpack). The problem I'm encountering, superficially, is

> Uncaught Error: hecs: component already registered 'Model'

However, I think this is a red herring. I believe webpack is not handling the `hecs-plugin-core` and `hecs-plugin-three` peerDependencies correctly, possibly resulting in multiple instances of the library.

Here is a repro: https://github.com/canadaduane/hecs-peerdeps-test

(`yarn && yarn dev`, then open in browser and see console)

I've tried various resolutions (this seemed to be the most promising: https://medium.com/@penx/managing-dependencies-in-a-node-package-so-that-they-are-compatible-with-npm-link-61befa5aaca7) but I'm still at a loss.

**Comment by ashconnell** [comment]
The component `Model` is already provided (and registered) by `hecs-plugin-three`

https://github.com/gohyperr/hecs/tree/master/packages/hecs-plugin-three/src/components

That is error is because your svelte app is trying to register another `Model` component with the same name

**Comment by ashconnell** [comment]
You're also trying to register a new ModelSystem etc too, which is also already provided by `hecs-plugin-three`. 

You can either use the ModelSystem and Model components provided by `hecs-plugin-three` so you don't have to write your own, or if you want to use custom ones you'll need to use a different name. The benefit of `hecs-plugin-three` is that you don't need to create these components and systems and they should provide everything you need to render models etc

**Comment by canadaduane** [comment]
Oh! I didn't even realize there could be naming collisions between plugins. Ok, thank you.
