### ISSUE TITLE
Get first entity & camera working

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#8]
I think I'm missing something obvious... but so far, I'm unable to get an entity (say, a Box) and camera working.

Here's what I'm trying:

```js
const world = new World({
  plugins: [ThreePlugin],
  systems: [],
  components: [],
});

world.presentation.setViewport(document.body);

// Create an entity
const entity = world.entities
  .create()
  .add(Transform)
  .add(Shape, {
    kind: "BOX",
    boxSize: new Vector3(1, 1, 1),
    color: "purple",
  })
  .activate();

// Create the singleton camera
const camera = world.entities
  .create()
  .add(Transform, {
    position: new Vector3(0, 100, 0),
  })
  .add(LookAt, {
    entity: entity.id,
    limit: "Y_AXIS",
  })
  .add(Camera)
  .activate();

const gameLoop = () => {
  world.update();
  requestAnimationFrame(gameLoop);
};

gameLoop();
```

When I inspect `world.presentation.scene.children`, I only see two light sources. My entity doesn't appear to be part of the scene hierarchy.

**Comment by canadaduane** [comment]
Has the way this works changed? (From the docs:)

> All entities with a Transform are given an Object3D component which will be displayed in the scene in the correct hierarchical position. This container is used internally for all Model and Shape meshes that are created.

**Comment by ashconnell** [comment]
What you have looks correct to me but I found a minor issue. You also need to include `CorePlugin` in your plugin dependencies like this:

```js
import ThreePlugin from 'hecs-plugin-three'
import CorePlugin from 'hecs-plugin-core'

const world = new World({
  plugins: [CorePlugin, ThreePlugin],
  systems: [],
  components: [],
});
```

I've actually gone and updated `hecs-plugin-three` and `hecs-plugin-physx` to automatically pull in `hecs-plugin-core` so if you just update from 0.14.0 to 0.16.0 your code above should work without any changes.

I also put together a working example here so it's easy to jump in and play around:

https://codesandbox.io/s/hecs-example-1-r1k67?file=/src/App.js

Hope this helps!

**Comment by ashconnell** [comment]
There's also something odd happening when you use a `LookAt` with a `Camera`. I haven't needed to use this yet so only just noticed.

The `LookAt` works correctly for all entity combinations except ones with a `Camera` on it. The rotation is somehow inverted. I've added an example and comments here: https://codesandbox.io/s/hecs-look-at-issue-4gqgd?file=/src/App.js

I do wonder if this is maybe how Three.js cameras work, the direction normal might be inverted.

**Comment by canadaduane** [comment]
That was it! The camera wasn't facing the entity.

**Comment by canadaduane** [comment]
> I do wonder if this is maybe how Three.js cameras work, the direction normal might be inverted.

Looks like your intuition was correct: https://github.com/mrdoob/three.js/issues/13753#issuecomment-378462743

**Comment by canadaduane** [comment]
I've added a PR for this at #10

**Comment by ashconnell** [comment]
Nice find!
